name: MineraFurnace
main: HannesTheDev\MineraFurnace\Main
version: 2.0.0
api: 3.0.0
author: HannesTheDev
description: "Cook, smelt, drie or bake an item in your hand"

commands:
  furnace:
    permission: "minerafurnace.furnace.cmd"
    description: "Cook, smelt, drie or bake a item in your hand"

permissions:
  minerafurnace.furnace.cmd:
    description: "Make /furnace"
    default: "op"
